controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

gallery_data:
  path: /gallery-data
  controller: App\Controller\GalleryController::galleryData

login:
  path: /login
  controller: App\Controller\SecurityController::app_login

show_rock:
  path: /{areaSlug}/{slug}
  controller: App\Controller\FrontendController::showRock

show_rocks:
  path: /{slug}
  controller: App\Controller\FrontendController::showRocksArea
